### ISSUE TITLE
Error installing remotes::install_github(“USAID-OHA-SI/glitr”)

### ISSUE THREAD

**Issue by mmdessie1** [USAID-OHA-SI/coRps#10]
Error: unexpected input in "remotes::install_github(“"

I was wondering what I am missing

**Comment by achafetz** [comment]
@mmdessie1 for some reason it doesn't seem to like the type of quotes. If you look at the code below, the top example is from what was  pulled from the issue title versus the bottom one was written out in R. You can see that the quotes are every so slightly different

```
remotes::install_github(“USAID-OHA-SI/glitr”) #not working
remotes::install_github("USAID-OHA-SI/glitr") #good
```

Try copying and pasting from the second example or typing this out in R/RStudio. I'm not sure what caused this.
